### ISSUE TITLE
P_on_surface.uasset is corrupt in 5.3 branch

### ISSUE THREAD

**Issue by AgentMilkshake1** [sideeffects/HoudiniNiagara#54]
Hi there, I believe that the P_on_surface.uasset is corrupt in the 5.3 branch as attempting to open the asset, or attempting to do a packaged build results in the following error:
`LoadErrors: Error: Unable to load package '/HoudiniNiagara/PointCache/P_on_surface'. The end of package tag is not valid. Check that the file is of the expected type and not corrupted.`

Please could a functioning version of this file be pushed to the 5.3 branch?

Many thanks.

**Comment by dpernuit** [comment]
Hi,

Yes, we're aware of the issue - and I reimported the asset recently.
But unfortunately, I'm having issues updating it here on Git.. 

I just put a new release on the repo here - the zipped binaries have a fixed version of the uasset.

**Comment by rlabrecquefsg** [comment]
This appears to still be an issue with the 5.3 branch specifically, because the file in HoudiniNiagara-v2.7-UE5.3-Win64.zip was saved with 5.4 and thus:

`LogAssetRegistry: Warning: Package F:/Redacted/Plugins/HoudiniNiagara/Content/PointCache/P_on_surface.uasset is too new. Engine Version: 1009  Package Version: 1012`
