### ISSUE TITLE
Support mobile platform?

### ISSUE THREAD

**Issue by islent** [sideeffects/HoudiniNiagara#7]
Thanks for this great work!
I'm working on data visualization with this plugin, and everything works on Windows. However, while shipping to android device, it just crash after Logo showed up. Then I saw the WINDOWS ONLY warning.

It would be much more better to investigate data on mobiles interactively, since niagara is already working on mobile in 4.25. Wondering whether this feature is on Todo list or not :D

**Comment by michela** [comment]
Any updates on this? There are some nice synergies between HOU support for UE4 USD and this but we'd want to see this work on mobile

**Comment by nanocell** [comment]
Niagara simulations using Houdini Point Caches _should_ be able to run on Mobile platforms provided the emitters have been set to *CPU* mode. GPU mode is likely out of the question due to memory and GPU compute buffer constraints -- I was not even able to run the simplest of Niagara systems in GPU mode on ES3.1 preview mode in the editor (4.27).
